CATEGORIES = [
    "🐘 Zvieratá",
    "🌍 Krajiny",
    "🍕 Jedlo",
    "⚽ Športy",
    "🎬 Filmy & Seriály",
    "👦 Mužské mená",
    "👧 Ženské mená",
    "🍳 Veci v kuchyni",
    "🏙️ Hlavné mestá",
    "🎵 Hudobné skupiny / Speváci",
    "🚗 Značky áut",
    "👗 Oblečenie & Módne značky",
    "🌿 Rastliny & Kvety",
    "💼 Povolania",
    "🎮 Videohry",
    "📱 Aplikácie & Technológie",
    "✈️ Krajiny v Európe",
    "🏖️ Dovolenkové destinácie",
    "🦸 Superhrdinovia",
    "🎓 Školské predmety",
    "🏠 Veci v obývačke",
    "🛒 Veci v supermarkete",
    "💊 Lieky & Zdravie",
    "🎨 Farby & Odtiene",
    "🌊 Veci v oceáne",
    "🪐 Vesmír & Planéty",
    "🍺 Nápoje",
    "🎪 Cirkus & Zábava",
    "🏰 Historické miesta",
    "💰 Značky & Firmy",
]
