CATEGORIES = [
    "🐘 Zvieratá",
    "🦁 Zvieratá v ZOO",
    "🐶 Domáce zvieratá",
    "🐟 Morské stvorenia",
    "🐦 Vtáky",
    "🦖 Dinosaury",
    "🐍 Plazy",
    "🐸 Obojživelníky",
    "🐛 Hmyz",

    "🌍 Krajiny",
    "🇪🇺 Krajiny Európy",
    "🌎 Krajiny Ameriky",
    "🌏 Krajiny Ázie",
    "🌍 Krajiny Afriky",
    "🇪🇺 Hlavné mestá Európy",
    "🏙️ Hlavné mestá sveta",
    "🗺️ Ostrovy",
    "🏔️ Pohoria",
    "🌋 Sopky",
    "🏝️ Ostrovy",
    "🌊 Oceány a moria",
    "🏞️ Rieky",
    "🏕️ Národné parky",
    "🏖️ Dovolenkové destinácie",

    "🍕 Jedlo",
    "🍔 Fast food",
    "🍰 Dezerty",
    "🍎 Ovocie",
    "🥕 Zelenina",
    "🥩 Mäso",
    "🧀 Syry",
    "🍞 Pečivo",
    "🌶️ Koreniny",
    "🍺 Nápoje",
    "🍷 Alkohol",
    "☕ Káva a čaje",

    "⚽ Športy",
    "🏟️ Športové tímy",
    "🏅 Olympijské športy",
    "🎾 Raketové športy",
    "🥊 Bojové športy",
    "🏎️ Motoršport",
    "🏊 Vodné športy",
    "⛷️ Zimné športy",

    "🎬 Filmy",
    "📺 Seriály",
    "🎭 Divadelné hry",
    "🎞️ Animované filmy",
    "📺 Televízne postavy",
    "🦸 Superhrdinovia",
    "🦹 Záporáci",
    "👸 Disney postavy",
    "🎬 Filmoví režiséri",
    "🎥 Herci",
    "🎭 Herečky",

    "📚 Názvy kníh",
    "✍️ Spisovatelia",
    "📖 Rozprávky",
    "📜 Slovenskí spisovatelia",

    "🎵 Speváci",
    "🎤 Speváčky",
    "🎼 Hudobné skupiny",
    "🎹 Hudobné nástroje",
    "🎧 Hudobné žánre",
    "🎶 Hudobné festivaly",

    "👦 Mužské mená",
    "👧 Ženské mená",
    "👶 Detské mená",

    "💼 Povolania",
    "👨‍⚕️ Zdravotnícke povolania",
    "👮 Uniformované povolania",
    "👨‍🍳 Gastronomické povolania",

    "🚗 Značky áut",
    "🏍️ Motocykle",
    "✈️ Lietadlá",
    "🚂 Vlaky",
    "🚢 Lode",
    "🚌 Dopravné prostriedky",

    "🏠 Časti domu",
    "🛋️ Veci v obývačke",
    "🍳 Veci v kuchyni",
    "🛏️ Veci v spálni",
    "🚿 Veci v kúpeľni",
    "🧹 Upratovacie potreby",
    "🔨 Náradie",
    "🌱 Záhradné náradie",

    "🛒 Veci v supermarkete",
    "✏️ Kancelárske potreby",
    "🎒 Školské pomôcky",
    "📚 Školské predmety",

    "👗 Oblečenie",
    "👟 Obuv",
    "👜 Módne značky",
    "⌚ Hodinky",
    "💍 Šperky",

    "🌿 Rastliny",
    "🌸 Kvety",
    "🌳 Stromy",
    "🌾 Poľnohospodárske plodiny",

    "💊 Lieky",
    "🩺 Časti tela",
    "🧬 Orgány",
    "🦠 Choroby",

    "🪐 Planéty",
    "⭐ Súhvezdia",
    "🌌 Vesmír",
    "🚀 Kozmonautika",

    "🎮 Videohry",
    "🕹️ Herné konzoly",
    "👾 Herné postavy",

    "📱 Mobilné aplikácie",
    "💻 Technológie",
    "🌐 Sociálne siete",
    "⌨️ Programovacie jazyky",

    "🏰 Hrady",
    "🏛️ Historické miesta",
    "📜 Historické obdobia",
    "👑 Panovníci",
    "⚔️ Historické osobnosti",

    "💰 Značky a firmy",
    "🏦 Banky",
    "🛍️ Obchodné reťazce",

    "🎨 Farby",
    "🖌️ Maliari",
    "🖼️ Umelecké smery",

    "📅 Mesiace v roku",
    "📆 Dni v týždni",
    "🎄 Sviatky",

    "⚛️ Prvky periodickej tabuľky",
    "🧪 Chemické látky",
    "🔬 Vedci",

    "🌦️ Počasie",
    "🌪️ Prírodné katastrofy",

    "🐉 Mýtické bytosti",
    "🧙 Fantasy postavy",

    "🎪 Cirkus",
    "🎭 Zábava",
    "🎲 Stolové hry",
    "🧩 Hračky",
]
